# Generated by Django 4.2.4 on 2023-12-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_about_remove_customuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_names',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
