# Generated by Django 4.2.4 on 2023-12-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_full_names_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
