# Generated by Django 4.2.4 on 2023-12-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_names',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_names',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
