# Generated by Django 4.2.4 on 2023-12-21 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmech',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestmech',
            name='mech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to=settings.AUTH_USER_MODEL),
        ),
    ]
