# Generated by Django 4.2.4 on 2023-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmech',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
