# Generated by Django 4.2.4 on 2023-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requestmech_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestmech',
            options={'ordering': ['-created_at']},
        ),
    ]
